// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt9ZnOKYOv0o7mrrbBV8PlrP4yIrp3r4I',
    appId: '1:327655105912:web:32181b80996d03d864948d',
    messagingSenderId: '327655105912',
    projectId: 'sanb-invoicing',
    authDomain: 'sanb-invoicing.firebaseapp.com',
    storageBucket: 'sanb-invoicing.appspot.com',
    measurementId: 'G-TM08JZP805',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCop1o2zuB4QLhzkesQszMP0dvbb46SfOw',
    appId: '1:327655105912:android:86d98f824f52534464948d',
    messagingSenderId: '327655105912',
    projectId: 'sanb-invoicing',
    storageBucket: 'sanb-invoicing.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUgJLErM1NHKsx74Yt61hF4l_TLWpqcYw',
    appId: '1:327655105912:ios:d6f4b06f98ba08c064948d',
    messagingSenderId: '327655105912',
    projectId: 'sanb-invoicing',
    storageBucket: 'sanb-invoicing.appspot.com',
    iosBundleId: 'com.arthurthirtyone.invoicingSandbWay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUgJLErM1NHKsx74Yt61hF4l_TLWpqcYw',
    appId: '1:327655105912:ios:d6f4b06f98ba08c064948d',
    messagingSenderId: '327655105912',
    projectId: 'sanb-invoicing',
    storageBucket: 'sanb-invoicing.appspot.com',
    iosBundleId: 'com.arthurthirtyone.invoicingSandbWay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt9ZnOKYOv0o7mrrbBV8PlrP4yIrp3r4I',
    appId: '1:327655105912:web:f6503f720b8e83ba64948d',
    messagingSenderId: '327655105912',
    projectId: 'sanb-invoicing',
    authDomain: 'sanb-invoicing.firebaseapp.com',
    storageBucket: 'sanb-invoicing.appspot.com',
    measurementId: 'G-DXXBV7SV0L',
  );
}
